live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x0f0f0f"
foreground = "0xd4be98"

[debug]
persistent_logging = false

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 13.0

[font.bold]
style = "Medium"

[font.bold_italic]
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 0
y = 0
