# ~/.config/starship.toml

# [character]
# error_symbol = "[✖](bold red) "

# [cmd_duration]
# min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
# format = " took [$duration]($style)"

# [directory]
# truncation_length = 5
# format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_commit]
commit_hash_length = 8
style = "bold white"

# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '

# [git_status]
# conflicted = "⚔️ "
# ahead = "🏎️ 💨 ×${count}"
# behind = "🐢 ×${count}"
# diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
# untracked = "🛤️  ×${count}"
# stashed = "📦 "
# modified = "📝 ×${count}"
# staged = "🗃️  ×${count}"
# renamed = "📛 ×${count}"
# deleted = "🗑️  ×${count}"
# style = "bright-white"
# format = "$all_status$ahead_behind"

# [hostname]
# ssh_only = false
# format = "<[$hostname]($style)>"
# trim_at = "-"
# style = "bold dimmed white"
# disabled = true

[julia]
symbol = "ஃ "
format = "[$symbol$version]($style) "
style = "bold green"

# [memory_usage]
# format = "$symbol[${ram}( | ${swap})]($style) "
# threshold = 70
# style = "bold dimmed white"
# disabled = false

# [package]
# disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

# [time]
# time_format = "%T"
# format = "$time($style) "
# style = "bright-white"
# disabled = false

# [username]
# style_user = "bold dimmed blue"
# show_always = false

[nodejs]
format = "[$symbol$version]($style) "
style = "bold green"

[character]
success_symbol = "[~](bold green)"
error_symbol = "[~](bold red)"
vicmd_symbol = "[](bold green)"

# [git_commit]
# tag_symbol = " tag "

[git_status]
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
renamed = "»"
deleted = "✘"
stashed = "$"
untracked = "?"

[aws]
symbol = "aws "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

# [git_branch]
# symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

# [julia]
# symbol = "jl "

[kotlin]
symbol = "kt "

# [nodejs]
# symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

# [python]
# symbol = "py "

[ruby]
symbol = "rb "

# [rust]
# symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
